Update chaining-jobs.yml

diff --git a/.github/workflows/chaining-jobs.yml b/.github/workflows/chaining-jobs.yml
--- a/.github/workflows/chaining-jobs.yml
+++ b/.github/workflows/chaining-jobs.yml
@@ -28,7 +28,8 @@ jobs:
       - name: Output for Job 2
         run: echo "Hello from Job 2"
       - name: Make Job 2 Fail
-        run: exit 1
+        # "exit 1" always ensures the job fails
+        run: exit 1 
     
   job-3:
     name: Job 3
